export const USER_FOUND = 'USER_FOUND';
export const USER_COUNT_FOUND = 'USER_COUNT_FOUND';
export const USER_NOT_FOUND = 'USER_NOT_FOUND';
export const REF_USER_LIST_FOUND = 'REF_USER_LIST_FOUND';
export const USER_CREATED = 'USER_CREATED';
export const USER_CREATED_WITH_REF = 'USER_CREATED_WITH_REF';


// ACTION
export const ACTION_CREATED = 'ACTION_CREATED';

export const BUY_A404 = 'BUY_A404';
export const REF_REWARD_BUY = 'REF_REWARD_BUY';

export const MINT_A404 = 'MINT_A404';
export const REF_REWARD_MINT = 'REF_REWARD_MINT';

export const REWARD_SUM_SUCCESS = 'REWARD_SUM_SUCCESS';
export const ACTION_LIST_FOUND = 'ACTION_LIST_FOUND';

// PINK_SELL_ORDER
export const PINK_SELL_ORDER_CREATED = 'PINK_SELL_ORDER_CREATED';
export const PINK_SELL_ORDER_UPDATED = 'PINK_SELL_ORDER_UPDATED';
export const PINK_SELL_ORDER_FOUND = 'PINK_SELL_ORDER_FOUND';
export const PINK_SELL_ORDER_LIST_FOUND = 'PINK_SELL_ORDER_LIST_FOUND';
export const ERROR_PINK_SELL_ORDER_POST_FAIL = 'ERROR_PINK_SELL_ORDER_POST_FAIL';


// PINK_BUY_ORDER
export const PINK_BUY_ORDER_CREATED = 'PINK_BUY_ORDER_CREATED';
export const PINK_BUY_ORDER_CREATE_FAIL = 'PINK_BUY_ORDER_CREATE_FAIL';
